### ISSUE TITLE
The Road to Completion

### ISSUE THREAD

**Issue by taisho6339** [taisho6339/gord#1]
## TODO
* [ ] Implement virtual node
* [x] Implement successor list
* [x] Implement leave node function
* [x] Implement join node function 
* [ ] Implement leave & join notification for applications which use gord
* [ ] Implement connection pooling for grpc
* [ ] Enable mTLS for internal connections
* [ ] Add limitation to grpc connection count

**Comment by taisho6339** [comment]
<img width="492" alt="スクリーンショット 2020-07-07 0 15 48" src="https://user-images.githubusercontent.com/1638833/86609612-1b06c300-bfe7-11ea-9c43-e63d478b7bb8.png">
